// Code generated by Gotmpl
// DO NOT EDIT, I MEAN IT'S USELESS :)

package main

import (
	__bytes "bytes"
	__html "html"
)

func Escape(html string, buffer *__bytes.Buffer) {
	buffer.WriteString(`<html>

<body>
    <!-- in text -->
    test ` + "`" + ` test
    <!-- in attributes -->
    <div class="foo` + "`" + `bar" style="style"></div>
    <!-- in script -->
    <script>
        console.log("` + "`" + `");
    </script>
    <!-- escape html -->
    `)
	buffer.WriteString(__html.EscapeString(html))
	buffer.WriteString(`
</body>

</html>
`)
}
